name: flex_mobile_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-62.0.dev <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  firebase_core: ^1.20.0
  firebase_auth: ^3.4.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  http: ^0.13.4
  mask_text_input_formatter: ^2.4.0
  flutter_barcode_scanner: ^2.0.0
  url_launcher: ^6.1.5
  get_it: ^7.2.0
  cloud_firestore: ^3.4.5
  group_radio_button: ^1.2.0
  number_inc_dec: ^0.8.0
  multiselect: ^0.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
